/*
  # CBE AI Data Analysis Platform - Complete Database Schema

  ## Overview
  This migration creates the complete database schema for the Commercial Bank of Ethiopia
  AI-powered Data Analysis & Transformation Platform.

  ## New Tables

  ### 1. `user_profiles`
  Extended user profile information linked to auth.users
  - `id` (uuid, primary key) - References auth.users
  - `email` (text) - User email
  - `full_name` (text) - User's full name
  - `role` (text) - Either 'admin' or 'business_user'
  - `status` (text) - Account status: 'pending', 'active', 'suspended'
  - `department` (text) - User's department
  - `created_at` (timestamptz) - Registration timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 2. `data_marts`
  Data mart definitions that users can query
  - `id` (uuid, primary key)
  - `name` (text) - Data mart name
  - `description` (text) - Business description
  - `database_type` (text) - Type of database (postgresql, mysql, etc.)
  - `connection_string` (text) - Encrypted connection details
  - `schema_metadata` (jsonb) - Table and column definitions
  - `is_active` (boolean) - Whether data mart is available
  - `created_by` (uuid) - Admin who created it
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)

  ### 3. `user_data_mart_access`
  Junction table managing which users can access which data marts
  - `id` (uuid, primary key)
  - `user_id` (uuid) - References user_profiles
  - `data_mart_id` (uuid) - References data_marts
  - `granted_by` (uuid) - Admin who granted access
  - `granted_at` (timestamptz)

  ### 4. `chat_conversations`
  Chat sessions between users and the AI
  - `id` (uuid, primary key)
  - `user_id` (uuid) - References user_profiles
  - `data_mart_id` (uuid) - Which data mart is being queried
  - `title` (text) - Conversation title (auto-generated from first query)
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)

  ### 5. `chat_messages`
  Individual messages within conversations
  - `id` (uuid, primary key)
  - `conversation_id` (uuid) - References chat_conversations
  - `role` (text) - Either 'user' or 'assistant'
  - `content` (text) - Message content
  - `query_type` (text) - Type of query (data_query, summary, chart, etc.)
  - `result_data` (jsonb) - Query results if applicable
  - `created_at` (timestamptz)

  ### 6. `query_logs`
  Audit trail of all queries executed
  - `id` (uuid, primary key)
  - `user_id` (uuid) - Who executed the query
  - `data_mart_id` (uuid) - Which data mart was queried
  - `conversation_id` (uuid) - Related conversation
  - `message_id` (uuid) - Related message
  - `natural_language_query` (text) - Original user question
  - `generated_sql` (text) - SQL generated by AI
  - `execution_time_ms` (integer) - Query execution time
  - `status` (text) - success, error, timeout
  - `error_message` (text) - Error details if failed
  - `created_at` (timestamptz)

  ## Security
  - Enable RLS on all tables
  - Admin users can access all data
  - Business users can only access their own data
  - Query logs are accessible only to admins and the user who created them
  - Data mart access is strictly controlled through the junction table
*/

-- Create enum types for better data integrity
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('admin', 'business_user');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE user_status AS ENUM ('pending', 'active', 'suspended');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE message_role AS ENUM ('user', 'assistant');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE query_status AS ENUM ('success', 'error', 'timeout');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- 1. User Profiles Table
CREATE TABLE IF NOT EXISTS user_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  full_name text NOT NULL,
  role user_role NOT NULL DEFAULT 'business_user',
  status user_status NOT NULL DEFAULT 'pending',
  department text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 2. Data Marts Table
CREATE TABLE IF NOT EXISTS data_marts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  database_type text DEFAULT 'postgresql',
  connection_string text,
  schema_metadata jsonb DEFAULT '{}',
  is_active boolean DEFAULT true,
  created_by uuid REFERENCES user_profiles(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 3. User Data Mart Access Table
CREATE TABLE IF NOT EXISTS user_data_mart_access (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,
  data_mart_id uuid REFERENCES data_marts(id) ON DELETE CASCADE,
  granted_by uuid REFERENCES user_profiles(id),
  granted_at timestamptz DEFAULT now(),
  UNIQUE(user_id, data_mart_id)
);

-- 4. Chat Conversations Table
CREATE TABLE IF NOT EXISTS chat_conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,
  data_mart_id uuid REFERENCES data_marts(id),
  title text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 5. Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid REFERENCES chat_conversations(id) ON DELETE CASCADE,
  role message_role NOT NULL,
  content text NOT NULL,
  query_type text,
  result_data jsonb,
  created_at timestamptz DEFAULT now()
);

-- 6. Query Logs Table
CREATE TABLE IF NOT EXISTS query_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,
  data_mart_id uuid REFERENCES data_marts(id),
  conversation_id uuid REFERENCES chat_conversations(id),
  message_id uuid REFERENCES chat_messages(id),
  natural_language_query text NOT NULL,
  generated_sql text,
  execution_time_ms integer,
  status query_status NOT NULL,
  error_message text,
  created_at timestamptz DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_profiles_role ON user_profiles(role);
CREATE INDEX IF NOT EXISTS idx_user_profiles_status ON user_profiles(status);
CREATE INDEX IF NOT EXISTS idx_data_marts_active ON data_marts(is_active);
CREATE INDEX IF NOT EXISTS idx_user_data_mart_access_user ON user_data_mart_access(user_id);
CREATE INDEX IF NOT EXISTS idx_user_data_mart_access_mart ON user_data_mart_access(data_mart_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversations_user ON chat_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation ON chat_messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_query_logs_user ON query_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_query_logs_created ON query_logs(created_at);

-- Enable Row Level Security
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_marts ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_data_mart_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE query_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies for user_profiles
CREATE POLICY "Users can view own profile"
  ON user_profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON user_profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Admins can view all profiles"
  ON user_profiles FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Admins can update all profiles"
  ON user_profiles FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can insert own profile on signup"
  ON user_profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

-- RLS Policies for data_marts
CREATE POLICY "Admins can view all data marts"
  ON data_marts FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Business users can view assigned data marts"
  ON data_marts FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_data_mart_access
      WHERE user_id = auth.uid() AND data_mart_id = data_marts.id
    )
  );

CREATE POLICY "Admins can insert data marts"
  ON data_marts FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Admins can update data marts"
  ON data_marts FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Admins can delete data marts"
  ON data_marts FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- RLS Policies for user_data_mart_access
CREATE POLICY "Admins can view all access grants"
  ON user_data_mart_access FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can view own access grants"
  ON user_data_mart_access FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Admins can manage access grants"
  ON user_data_mart_access FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Admins can delete access grants"
  ON user_data_mart_access FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- RLS Policies for chat_conversations
CREATE POLICY "Users can view own conversations"
  ON chat_conversations FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Admins can view all conversations"
  ON chat_conversations FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can create own conversations"
  ON chat_conversations FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own conversations"
  ON chat_conversations FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own conversations"
  ON chat_conversations FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- RLS Policies for chat_messages
CREATE POLICY "Users can view messages in own conversations"
  ON chat_messages FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM chat_conversations
      WHERE id = chat_messages.conversation_id AND user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can view all messages"
  ON chat_messages FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can insert messages in own conversations"
  ON chat_messages FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM chat_conversations
      WHERE id = chat_messages.conversation_id AND user_id = auth.uid()
    )
  );

-- RLS Policies for query_logs
CREATE POLICY "Users can view own query logs"
  ON query_logs FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Admins can view all query logs"
  ON query_logs FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Users can insert own query logs"
  ON query_logs FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- Create trigger to auto-update updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_profiles_updated_at
  BEFORE UPDATE ON user_profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_data_marts_updated_at
  BEFORE UPDATE ON data_marts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_chat_conversations_updated_at
  BEFORE UPDATE ON chat_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();